import { OntologyClass } from '@/lib/api/ontology_api/types';

export const xsdTypes: OntologyClass[] = [
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#string',
    label: [{ value: 'string' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#boolean',
    label: [{ value: 'boolean' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#decimal',
    label: [{ value: 'decimal' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#float',
    label: [{ value: 'float' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#double',
    label: [{ value: 'double' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#duration',
    label: [{ value: 'duration' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#dateTime',
    label: [{ value: 'dateTime' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#time',
    label: [{ value: 'time' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#date',
    label: [{ value: 'date' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#gYearMonth',
    label: [{ value: 'gYearMonth' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#gYear',
    label: [{ value: 'gYear' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#gMonthDay',
    label: [{ value: 'gMonthDay' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#gDay',
    label: [{ value: 'gDay' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#gMonth',
    label: [{ value: 'gMonth' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#hexBinary',
    label: [{ value: 'hexBinary' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#base64Binary',
    label: [{ value: 'base64Binary' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#anyURI',
    label: [{ value: 'anyURI' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#QName',
    label: [{ value: 'QName' }],
    super_classes: [],
    is_deprecated: false,
  },
  {
    type: 'class',
    belongs_to: 'http://www.w3.org/2001/XMLSchema#',
    description: [],
    full_uri: 'http://www.w3.org/2001/XMLSchema#NOTATION',
    label: [{ value: 'NOTATION' }],
    super_classes: [],
    is_deprecated: false,
  },
];
